drop table ORDER_ITEMS if exists;
drop table ORDERS if exists;
drop table MOBILEPHONES if exists;
drop table PRODUCERS if exists;


CREATE TABLE PRODUCERS(
    producer_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    producer_name VARCHAR (50),

    PRIMARY KEY(producer_id)
);

CREATE TABLE MOBILEPHONES(
    mobile_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    name VARCHAR (100),
    cost DECIMAL (10, 0),
    producer_id INTEGER,

    PRIMARY KEY(mobile_id)
);

CREATE TABLE ORDERS(
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    order_id VARCHAR (16) NOT NULL,
    delivered_status BOOLEAN,
    delivery_price DECIMAL (10,0),
    total_cost DECIMAL (10,0),
    first_name VARCHAR (50),
    last_name VARCHAR (50),
    phone_number VARCHAR (50),

    PRIMARY KEY(id),
    UNIQUE (order_id)
);


CREATE TABLE ORDER_ITEMS(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    order_id VARCHAR (16) ,
    product_id INTEGER,
    amount INTEGER ,
    price_for_one DECIMAL (10,0),

    PRIMARY KEY (id),

    FOREIGN KEY (order_id) REFERENCES ORDERS(order_id),
    FOREIGN KEY (product_id) REFERENCES MOBILEPHONES(mobile_id)
);
